Web muhammed
bounswe/2021SpringGroup1 pull request #140
Opened 2021-11-12 15:01 UTC by gktpmuhammed

Landing page is ready. Please review and give feedback.

2021-11-12 15:02 UTC, emiroztoprak commented
All the changes seem to be working correctly. I think it is ready to merge.

2021-11-12 15:16 UTC, 4teko7 requested changes

2021-11-12 15:16 UTC, 4teko7 commented on Web/src/screens/bootstrap.js
> +import SideBar from 'components/navbar/SideBar';
You should remove SideBar from bootstrap screen. It is already in navigation.

2021-11-12 15:16 UTC, 4teko7 commented on Web/src/screens/bootstrap.js
> +<SideBar />
This component is not necessary

2021-11-12 15:16 UTC, 4teko7 commented on Web/src/components/SignUpForm.js
> +function Form() {
We are using React-Bootstrap. You should use components of React-Bootstrap. There are tons of components there. Currentlyi you are using normal html tags not components.

2021-11-12 15:16 UTC, 4teko7 commented on Web/src/components/LoginForm.js
> +function Form() {
We are using React-Bootstrap. You should use components of React-Bootstrap. There are tons of components there. Currentlyi you are using normal html tags not components.

2021-11-12 15:16 UTC, 4teko7 commented on Web/src/App.css
> +
Don't put lots of css in App.css
This file is valid for all pages. You should use component based css files. I mean, form.css login.css etc. can be created for some components. React-Bootstrap gives you lots of flexibility. You don't need to you lots of css.

2021-11-12 15:16 UTC, 4teko7 commented on Web/src/screens/landingPage.js
> +        </figure></div><div class="col-md-4"> <figure> <img class="img-fluid" src="https://i4.hurimg.com/i/hurriyet/75/1110x740/5b8e6d967152d827603dd434.jpg" alt=""/>
With a map function you can create this lines.
let LINKS = [https://i4.hurimg.com/i/hurriyet/75/1110x740/5b8e6d967152d827603dd434.jpg, https://i4.hurimg.com/i/hurriyet/75/1110x740/5b8e6d967152d827603dd434.jpg,]
let FIGURES = []
LINKS.map(res => {
  FIGURES.push(
    <figure> <img class="img-fluid" src= `${res}` alt=""/> 
  )
})

{FIGURES}

2021-11-13 21:53 UTC, gktpmuhammed commented
I will close this pull request and open a new one. I have corrected some files based on the feedback from Bilal. I have added new functionalities aslo.

2021-11-13 21:53 UTC, closed without merging