Implementing User Home Feed , Searching Communities and changes on test.py
bounswe/2021SpringGroup1 pull request #195
Opened 2021-12-08 19:33 UTC by emrahdgn

I implemented GetUserHomeFeed and SearchCommunities functions. 
GetUserHomeFeed function returns the posts in the communities where the user is registered, from newest to oldest.
The SearchCommunities function returns the names of communities which contains the given text.

In the swagger documentation, for SearchCommunities function there are some extra fields in automatic Responses rendering part. It needs to be fixed. But there are no functionality problem. The function return only community names as expected.

I added GetUserHomeFeed function tests. Also, in test.py there are some failures from previous test functions due to identity mismatch and comparison of OrderedDict to Dictionary. I fixed them.

Moreover, i added  Location and Date data types.

2021-12-08 21:47 UTC, MrLebowski42 requested changes
It looks quite good but there are some small issues that needs some changes. After fixing those, we can merge.

2021-12-08 21:47 UTC, MrLebowski42 commented on cmpe451/protopost/views.py
>              return Response({"Success":False, "Error": "No Authentication"})
Cool implementation! I think QuerySet objects have their own sorting method but it looks quite good.

2021-12-08 21:47 UTC, MrLebowski42 commented on cmpe451/protopost/views.py
> +
Why do this method only returns names of the communities? I think it should be returning an array of community objects. If you return `communities.data` instead of `community_names` it should be good to go.

2021-12-08 21:47 UTC, MrLebowski42 commented on cmpe451/protopost/tests.py
> +# #             self.client.post("/create_community", {"name":f"test_grubu_{i}","description":f"Test grub {i} description.","is_private":False})
We can delete these comments.

2021-12-08 21:47 UTC, MrLebowski42 commented on cmpe451/protopost/tests.py
> +# #         self.assertEqual(response.json()["Community"][0]["is_private"], False)
We can also delete these comments too.

2021-12-09 05:17 UTC, emrahdgn commented on cmpe451/protopost/views.py
> +
The reason i returned only the names of communities is [Backend-API-Sketch](https://github.com/bounswe/2021SpringGroup1/wiki/Backend-API-Sketch-for-Milestone-1).
In this sketch it is stated that only the names of the communities should be returned.

Actually, returning an array of community objects makes more sense to me as well.If we decide in this way, it can be solved by changing 1 line as you stated.

2021-12-09 05:26 UTC, emrahdgn commented on cmpe451/protopost/views.py
>              return Response({"Success":False, "Error": "No Authentication"})
First of all thanks. Yes, you are right, there are some sorting methods that can be tried. 
I'd like it to stay that way for now to allow more time for the front-end parties to hook up the function. However, I think we can use these sorting methods in the future.

2021-12-09 06:59 UTC, MrLebowski42 commented on cmpe451/protopost/views.py
> +
> The reason i returned only the names of communities is [Backend-API-Sketch](https://github.com/bounswe/2021SpringGroup1/wiki/Backend-API-Sketch-for-Milestone-1). In this sketch it is stated that only the names of the communities should be returned.

That is logical but sketch is somewhat obsolete. I think going with returning the whole community object would be better.

2021-12-09 08:11 UTC, MrLebowski42 approved these changes
I think it looks quite good. We can merge this branch.

2021-12-09 08:14 UTC, MrLebowski42 commented on cmpe451/protopost/views.py
>              return Response({"Success":False, "Error": "No Authentication"})
On second thought, this approach may be more sound than the built-in methods so good call.

2021-12-09 09:45 UTC, merged